server:
  port: 8088
spring:
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
  datasource:
    name: dataSource
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: michael
    password: iknowwo
    # 使用c3p0数据库连接池
#    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:com/cc/mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.cc.model  # 注意：对应实体类的路径

#logging:
##    file:   # 日志文件,绝对路径或相对路径
##    path:   # 保存日志文件目录路径
##  config: # 日志配置文件,Spring Boot默认使用classpath路径下的日志配置文件,如:logback.xml
#  level:  # 日志级别
#    org.springframework.web: DEBUG



